### ISSUE TITLE
Middleware returns empty content

### ISSUE THREAD

**Issue by overint** [spatie/laravel-pjax#14]
Hi!

I'm trying to get this set up on a fresh laravel 5.2 installation, however I cannot get it working.
There seems to be a problem with the response not being set to the correct content. The following block of code is responsible:

```
$response->setContent(
    $this->makeTitle($crawler).
    $this->fetchContainer($crawler, $container)
);
```

If I check the output of the makeTitle and fetchContainer functions, both correctly extract and return, however all requests come back with empty content (however the correct headers are set).

Any idea what could be causing this problem?

**Comment by sebastiandedeyne** [comment]
Sorry for never responding here. Gonna close this for inactivity. Feel free to open if you still need help!
