### ISSUE TITLE
Some views needs to be refreshed to see the correct content (CSS issue?)

### ISSUE THREAD

**Issue by eugenevdm** [spatie/laravel-pjax#18]
Hi,

I use this plugin, but even the vanilla code from Laracasts causes the same issue.

The issue is, some pages, and always the same pages, show incorrect content. The content that is missing is Javascript per page scripts. For example, I have an Orgchart page. This uses Google's Chart API to draw an org chart. It loads on a certain page and initialises the names of the people from a controller that sends data to the view.

Is there an easy workaround?

**Comment by sebastiandedeyne** [comment]
Sounds like your JavaScript needs to be re-executed after a pjax call. You can do this by registering an event listener in pjax, check out their readme for a more detailed explanation.

https://github.com/defunkt/jquery-pjax#reinitializing-pluginswidget-on-new-page-content
