### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rexdarel** [spatie/laravel-pjax#19]
HI I followed the instructions but it seems like I have a problem with this.
I imported the js scripts jquery.min.js and jquery.pjax.js in my app.blade.php
I also put this inside in script tag in my app.blade.php
`$(document).pjax('a', '#pjax-container');`
and put an id pjax-container on my div tag
but everytime I go to the chat link it will still refresh the whole page and vice versa if I go to profile page. I checked the Network in inspect element I got this error
**Name : http://circle.dev/profile?_pjax=%23pjax-container
Status: 500 Internal server error**

Any idea on how to fix this?
PS. my laravel project is 5.5 I just want to integrate the pjax to load faster

**Comment by sebastiandedeyne** [comment]
If you're still having issues here, please share a full stack trace of your error so I can debug it from there.

**Comment by ngrcode** [comment]
hi I have this error in pjax after installing crawler 
The current node list is empty.
I dont know how to fix it

**Comment by sebastiandedeyne** [comment]
Please share the stack trace of the server error.

**Comment by ngrcode** [comment]
I have exactly the same error and my pjax version is 2.0.1
what can I do please help me

**Comment by sebastiandedeyne** [comment]
The original poster received a 500 status code from the server. I can't help without seeing a stack trace of that error.

**Comment by ngrcode** [comment]
this is my error  InvalidArgumentException
The current node list is empty.

**Comment by ngrcode** [comment]
and this is my added middleware of jeffry


<?php
namespace App\Http\Middleware;
use Closure;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Symfony\Component\DomCrawler\Crawler;
class PjaxMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  Request $request
     * @param  Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        if (! $request->pjax() || $response->isRedirection()) {
            return $response;
        }
        $this->filterResponse($response, $request->header('X-PJAX-CONTAINER'))
            ->setUriHeader($response, $request);
        return $response;
    }
    /**
     * Prepare the PJAX-specific response content.
     *
     * @param  Response $response
     * @param  string   $container
     * @return $this
     */
    protected function filterResponse(Response $response, $container)
    {
        $crawler = new Crawler($response->getContent());
        $response->setContent(
            $this->makeTitle($crawler) .
            $this->fetchContents($crawler, $container)
        );
        return $this;
    }
    /**
     * Prepare an HTML title tag.
     *
     * @param  Crawler $crawler
     * @return string
     */
    protected function makeTitle($crawler)
    {
        $pageTitle = $crawler->filter('head > title')->html();
        return "<title>{$pageTitle}</title>";
    }
    /**
     * Fetch the PJAX-specific HTML from the response.
     *
     * @param  Crawler $crawler
     * @param  string  $container
     * @return string
     */
    protected function fetchContents($crawler, $container)
    {
        $content = $crawler->filter($container);
        if (! $content->count()) {
            abort(422);
        }
        return $content->html();
    }
    /**
     * Set the PJAX-URL header to the current uri.
     *
     * @param Response $response
     * @param Request  $request
     */
    protected function setUriHeader(Response $response, Request $request)
    {
        $response->header(
            'X-PJAX-URL', $request->getRequestUri()
        );
    }
}

**Comment by ngrcode** [comment]
please help me
