### ISSUE TITLE
Middleware prority

### ISSUE THREAD

**Issue by iainheng** [spatie/laravel-pjax#24]
I have a middleware only apply to a controller but I want my middleware to execute before pjax's middleware. 

Example code of my middleware:

```php
public function handle($request, Closure $next)
{
        $booking = session()->get('booking');

        if (!$booking) {
            $request->session()->flash('alert-warning', 'Your session is expired.');

            $request->headers->remove('X-PJAX');

            return redirect()->route('booking.index');
        }

        return $next($request);
}
```

The purpose of my middleware is to disable PJAX and redirect with normal request if my session variable is empty. 

Do you have any idea to achieve this?

**Comment by freekmurze** [comment]
I'm not sure, but I suspect the order of registering the middleware in the Kernel is respected.

**Comment by iainheng** [comment]
Thanks. I was looking at the `$middlewarePriority` property in `Kernel` but I don't feel like overriding it. So I end up created another `$middlewareGroups` just for PJAX enabled routes 

```
'pjax' => [
            ValidateBookingSession::class,
            \Spatie\Pjax\Middleware\FilterIfPjax::class
        ],
``
