### ISSUE TITLE
mix

### ISSUE THREAD

**Issue by akinolu52** [spatie/laravel-pjax#27]
is it compulsory to use mix? is there another alternative to the mix in the demo?

and is this package https://github.com/defunkt/jquery-pjax needed before laravel-pjax can work
@freekmurze

**Comment by sebastiandedeyne** [comment]
This library only handles the backend side of pjax. You'll need a JS pjax library to get this to work, so yes, you'll need to add jquery-pjax or an alternative) to your app.
