### ISSUE TITLE
How to handle JsonResponses? or is this a bug

### ISSUE THREAD

**Issue by raftalks** [spatie/laravel-pjax#29]
I am facing this issue where if session gets expired or an exception gets thrown, the middleware FilterIfPjax::filterResponse throws the following error. 

Spatie\Pjax\Middleware\FilterIfPjax::filterResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given

What is the best way to handle this problem? I have only noticed this issue when accessing a route using pjax call if the user session gets expired or an exception like UnauthorizedException gets thrown.

**Comment by juliangums** [comment]
@raftalks how did you solve this?
