### ISSUE TITLE
install error.

### ISSUE THREAD

**Issue by sunny-kevin** [spatie/laravel-pjax#37]
composer require spatie/laravel-pjax
Using version ^2.0 for spatie/laravel-pjax
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install spatie/laravel-pjax 2.0.1
    - Conclusion: remove symfony/css-selector v5.0.1
    - Installation request for spatie/laravel-pjax ^2.0 -> satisfiable by spatie/laravel-pjax[2.0.0, 2.0.1].
    - Conclusion: don't install symfony/css-selector v5.0.1
.....
    - Installation request for symfony/css-selector (locked at v5.0.1) -> satisfiable by symfony/css-selector[v5.0.1].

**Comment by freekmurze** [comment]
I accept a PR that fixes this

**Comment by sfavorite** [comment]
I submitted a pull request yesterday, Dec 9th, that will fix this.
